

try:
    print(a)
except Exception as e:
    print(e)


print("hello")